// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// publish_tde
void publish_tde(std::wstring filename, std::wstring datasource, std::wstring hostname, std::wstring username, std::wstring password, std::wstring siteID, std::wstring project, bool overwrite);
RcppExport SEXP rtableau_publish_tde(SEXP filenameSEXP, SEXP datasourceSEXP, SEXP hostnameSEXP, SEXP usernameSEXP, SEXP passwordSEXP, SEXP siteIDSEXP, SEXP projectSEXP, SEXP overwriteSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::wstring >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type datasource(datasourceSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type hostname(hostnameSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type siteID(siteIDSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type project(projectSEXP);
    Rcpp::traits::input_parameter< bool >::type overwrite(overwriteSEXP);
    publish_tde(filename, datasource, hostname, username, password, siteID, project, overwrite);
    return R_NilValue;
END_RCPP
}
// WriteTDE
void WriteTDE(Rcpp::DataFrame df, std::vector<std::string> coltypes, std::wstring filename);
RcppExport SEXP rtableau_WriteTDE(SEXP dfSEXP, SEXP coltypesSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type coltypes(coltypesSEXP);
    Rcpp::traits::input_parameter< std::wstring >::type filename(filenameSEXP);
    WriteTDE(df, coltypes, filename);
    return R_NilValue;
END_RCPP
}
