# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Publish a Tableau Data Extract (.tde) file to a Tableau Server
#'  using the Tableau SDK.
#'
#' @param filename a valid .tde file to publish
#' @param datasource what you want to name your extract on the server
#' @param hostname the full hostname of your Tableau Server
#' @param username Tableau Server username
#' @param password Tableau Server password
#' @param siteID The site ID, use empty string for the default site
#' @param project The name of the project on Tableau Server to publish to.
#'  If unspecified it will publish to the default project
#' @param overwrite logical. If TRUE, any existing extract with the
#'  same datasource name is destroyed. If FALSE, it will only publish
#'  if the datasource name does not already exist.
#'
#' @export
#'
#' @examples
#' publish_tde(iris, "iris.tde", "Iris", "http://localhost", "username", "password")
#'
publish_tde <- function(filename, datasource, hostname, username, password, siteID, project, overwrite = FALSE) {
    invisible(.Call('rtableau_publish_tde', PACKAGE = 'rtableau', filename, datasource, hostname, username, password, siteID, project, overwrite))
}

.WriteTDE <- function(df, coltypes, filename) {
    invisible(.Call('rtableau_WriteTDE', PACKAGE = 'rtableau', df, coltypes, filename))
}

